"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

'''
RUN this command if libaries not compile and link
python3 -m pip install --only-binary=:all: {Import name }
'''
from setuptools import setup

APP = ['YTDownloader.py']
DATA_FILES = [('resources', ['resources/ffmpeg', 'resources/ffprobe'])]
OPTIONS = {
    'iconfile':'AppIcon.icns',
    'includes': ['ffmpeg', 'ffprobe'],
}

setup(
    name="VidDownloader",
    version="0.2",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
